name       : gcab
version    : 0.6
release    : 1
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gcab/0.6/gcab-0.6.tar.xz : a0443b904bfa7227b5155bfcdf9ea9256b6e26930b8febe1c41f972f6f1334bb
license    : LGPL-2.1
summary    : GLib Cabinet API
description: |
    GLib Cabinet API
builddeps  :
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
