name       : gcab
version    : '0.7'
release    : 3
source     :
    - https://download.gnome.org/sources/gcab/0.7/gcab-0.7.tar.xz : a16e5ef88f1c547c6c8c05962f684ec127e078d302549f3dfd2291e167d4adef
license    : LGPL-2.1-or-later
component  : system.utils
summary    : GLib Cabinet API
description: |
    GLib Cabinet API
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
