name       : gcab
version    : '1.6'
release    : 6
source     :
    - https://download.gnome.org/sources/gcab/1.6/gcab-1.6.tar.xz : 2f0c9615577c4126909e251f9de0626c3ee7a152376c15b5544df10fc87e560b
homepage   : https://gitlab.gnome.org/GNOME/gcab
license    : LGPL-2.1-or-later
component  : system.utils
summary    : A GObject library to create cabinet files
description: |
    A GObject library to create cabinet files
builddeps  :
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
