name       : gcab
version    : '1.5'
release    : 5
source     :
    - https://download.gnome.org/sources/gcab/1.5/gcab-1.5.tar.xz : 46bf7442491faa4148242b9ec2a0786a5f6e9effb1b0566e5290e8cc86f00f0c
homepage   : https://gitlab.gnome.org/GNOME/gcab
license    : LGPL-2.1-or-later
component  : system.utils
summary    : A GObject library to create cabinet files
description: |
    A GObject library to create cabinet files
builddeps  :
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
