name       : gcab
version    : '1.4'
release    : 4
source     :
    - https://download.gnome.org/sources/gcab/1.4/gcab-1.4.tar.xz : 67a5fa9be6c923fbc9197de6332f36f69a33dadc9016a2b207859246711c048f
homepage   : https://gitlab.gnome.org/GNOME/gcab
license    : LGPL-2.1-or-later
component  : system.utils
summary    : A GObject library to create cabinet files
description: |
    A GObject library to create cabinet files
builddeps  :
    - pkgconfig(gtk-doc)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
